import {
  Astro,
  Audio,
  BracketsBlue,
  BracketsPink,
  BracketsPurple,
  BracketsYellow,
  Bun,
  CLang,
  CMake,
  CodeOrange,
  Cplus,
  Csharp,
  Csv,
  Database,
  Deno,
  Docker,
  Document,
  EditorConfig,
  Eslint,
  Font,
  Git,
  Go,
  Gradle,
  Graphql,
  Haskell,
  Hugo,
  Image,
  Java,
  Jest,
  Js,
  Julia,
  Kotlin,
  License,
  Liquid,
  Lock,
  Lua,
  Markdown,
  MDX,
  Next,
  Nim,
  Nix,
  Node,
  Notebook,
  NPM,
  Nuxt,
  PDF,
  PHP,
  PNPM,
  PostCSS,
  Prettier,
  Prisma,
  Python,
  Reactjs,
  Reactts,
  Ruby,
  Rust,
  Shell,
  Solidity,
  Storybook,
  Svelte,
  SVG as SvgIcon,
  Swift,
  Tailwind,
  Terraform,
  Text,
  Tsconfig,
  TypeScript,
  Video,
  Vite,
  Vlang,
  Vue,
  Webpack,
  XML,
  Yaml,
  Yarn,
  Zig,
  Zip,
} from "@react-symbols/icons/files";
import {
  Folder,
  FolderApp,
  FolderAssets,
  FolderClaude,
  FolderConfig,
  FolderConstants,
  FolderContext,
  FolderCore,
  FolderCypress,
  FolderDatabase,
  FolderDocker,
  FolderDocuments,
  FolderGithub,
  FolderHelpers,
  FolderHooks,
  FolderImages,
  FolderInterfaces,
  FolderJs,
  FolderLayout,
  FolderLock,
  FolderModels,
  FolderModules,
  FolderNodeModules,
  FolderOpen,
  FolderPrisma,
  FolderProviders,
  FolderReact,
  FolderRouter,
  FolderServices,
  FolderShared,
  FolderSrc,
  FolderSupabase,
  FolderUtils,
  FolderVercel,
  FolderVSCode,
} from "@react-symbols/icons/folders";
import type { ComponentType, SVGProps } from "react";

/*
 * File-tree icon registry. Wraps `@react-symbols/icons` (Symbols by Miguel
 * Solorio, ported to React by pheralb, MIT). Each entry is an SVG component
 * that renders the same colored icon the upstream Symbols icon set uses, so
 * the FileTree pane gets familiar language colors at a glance.
 *
 * Color-rich iconography is otherwise avoided UI-wide; this is a deliberate
 * exception scoped to the FileTree pane only -- language colors are one of
 * the most useful visual scans in a code-focused tool.
 */

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

const EXTENSION_ICONS: Record<string, IconComponent> = {
  ts: TypeScript,
  tsx: Reactts,
  mts: TypeScript,
  cts: TypeScript,
  js: Js,
  jsx: Reactjs,
  mjs: Js,
  cjs: Js,
  // JSON renders as yellow curly brackets to match the `{ }` data shape
  // (and to visually distinguish it from JS files which use the JS logo).
  json: BracketsYellow,
  jsonc: BracketsYellow,
  py: Python,
  pyi: Python,
  rs: Rust,
  go: Go,
  java: Java,
  kt: Kotlin,
  swift: Swift,
  c: CLang,
  h: CLang,
  cpp: Cplus,
  hpp: Cplus,
  cc: Cplus,
  cs: Csharp,
  rb: Ruby,
  php: PHP,
  lua: Lua,
  jl: Julia,
  hs: Haskell,
  nim: Nim,
  nix: Nix,
  zig: Zig,
  v: Vlang,
  sol: Solidity,
  cmake: CMake,
  vue: Vue,
  svelte: Svelte,
  astro: Astro,
  liquid: Liquid,
  // react-symbols has no dedicated HTML / CSS icons. HTML uses the angle-
  // bracket Code icon (matches the `<tag>` syntax). CSS / SCSS / LESS use
  // the curly-brace Brackets icons (matches `{ }` rule blocks).
  html: CodeOrange,
  htm: CodeOrange,
  css: BracketsBlue,
  scss: BracketsPink,
  sass: BracketsPink,
  less: BracketsPurple,
  md: Markdown,
  mdx: MDX,
  markdown: Markdown,
  txt: Text,
  ipynb: Notebook,
  yaml: Yaml,
  yml: Yaml,
  toml: Document,
  ini: Document,
  cfg: Document,
  conf: Document,
  env: Document,
  sh: Shell,
  bash: Shell,
  zsh: Shell,
  fish: Shell,
  ps1: Shell,
  bat: Shell,
  sql: Database,
  db: Database,
  sqlite: Database,
  png: Image,
  jpg: Image,
  jpeg: Image,
  gif: Image,
  webp: Image,
  ico: Image,
  bmp: Image,
  svg: SvgIcon,
  pdf: PDF,
  zip: Zip,
  tar: Zip,
  gz: Zip,
  mp3: Audio,
  wav: Audio,
  flac: Audio,
  ogg: Audio,
  m4a: Audio,
  mp4: Video,
  webm: Video,
  mkv: Video,
  mov: Video,
  ttf: Font,
  otf: Font,
  woff: Font,
  woff2: Font,
  csv: Csv,
  tsv: Csv,
  xml: XML,
  graphql: Graphql,
  gql: Graphql,
  lock: Lock,
  log: Document,
};

const NAMED_FILE_ICONS: Record<string, IconComponent> = {
  "package.json": NPM,
  "package-lock.json": NPM,
  "pnpm-lock.yaml": PNPM,
  "pnpm-workspace.yaml": PNPM,
  "yarn.lock": Yarn,
  "bun.lockb": Bun,
  "bun.lock": Bun,
  ".gitignore": Git,
  ".gitattributes": Git,
  ".gitmodules": Git,
  ".gitkeep": Git,
  ".dockerignore": Docker,
  dockerfile: Docker,
  "docker-compose.yml": Docker,
  "docker-compose.yaml": Docker,
  "tsconfig.json": Tsconfig,
  "tsconfig.base.json": Tsconfig,
  "tsconfig.build.json": Tsconfig,
  "vite.config.ts": Vite,
  "vite.config.js": Vite,
  "vite.config.mjs": Vite,
  "vitest.config.ts": Vite,
  "vitest.config.js": Vite,
  "next.config.js": Next,
  "next.config.ts": Next,
  "next.config.mjs": Next,
  "nuxt.config.ts": Nuxt,
  "tailwind.config.js": Tailwind,
  "tailwind.config.ts": Tailwind,
  "postcss.config.js": PostCSS,
  "postcss.config.cjs": PostCSS,
  "postcss.config.ts": PostCSS,
  ".eslintrc": Eslint,
  ".eslintrc.js": Eslint,
  ".eslintrc.json": Eslint,
  ".eslintrc.cjs": Eslint,
  "eslint.config.js": Eslint,
  "eslint.config.mjs": Eslint,
  "eslint.config.ts": Eslint,
  ".prettierrc": Prettier,
  ".prettierrc.json": Prettier,
  ".prettierrc.js": Prettier,
  "prettier.config.js": Prettier,
  ".editorconfig": EditorConfig,
  ".node-version": Node,
  ".nvmrc": Node,
  "deno.json": Deno,
  "deno.jsonc": Deno,
  "cargo.toml": Rust,
  "cargo.lock": Rust,
  "go.mod": Go,
  "go.sum": Go,
  "build.gradle": Gradle,
  "build.gradle.kts": Gradle,
  "settings.gradle": Gradle,
  "schema.prisma": Prisma,
  makefile: Document,
  rakefile: Ruby,
  "readme.md": Markdown,
  "readme.mdx": MDX,
  "changelog.md": Markdown,
  license: License,
  "license.md": License,
  "license.txt": License,
  ".env": Document,
  ".env.local": Document,
  ".env.example": Document,
  ".env.development": Document,
  ".env.production": Document,
  "webpack.config.js": Webpack,
  "webpack.config.ts": Webpack,
  "jest.config.js": Jest,
  "jest.config.ts": Jest,
  "jest.config.mjs": Jest,
  "storybook.config.ts": Storybook,
  "main.tf": Terraform,
  "hugo.toml": Hugo,
};

const NAMED_FOLDER_ICONS: Record<
  string,
  { closed: IconComponent; opened: IconComponent }
> = {
  ".git": { closed: Git as IconComponent, opened: Git as IconComponent },
  ".github": { closed: FolderGithub, opened: FolderGithub },
  ".vscode": { closed: FolderVSCode, opened: FolderVSCode },
  ".claude": { closed: FolderClaude, opened: FolderClaude },
  ".vercel": { closed: FolderVercel, opened: FolderVercel },
  src: { closed: FolderSrc, opened: FolderSrc },
  source: { closed: FolderSrc, opened: FolderSrc },
  app: { closed: FolderApp, opened: FolderApp },
  apps: { closed: FolderApp, opened: FolderApp },
  config: { closed: FolderConfig, opened: FolderConfig },
  configs: { closed: FolderConfig, opened: FolderConfig },
  constants: { closed: FolderConstants, opened: FolderConstants },
  context: { closed: FolderContext, opened: FolderContext },
  contexts: { closed: FolderContext, opened: FolderContext },
  core: { closed: FolderCore, opened: FolderCore },
  cypress: { closed: FolderCypress, opened: FolderCypress },
  database: { closed: FolderDatabase, opened: FolderDatabase },
  db: { closed: FolderDatabase, opened: FolderDatabase },
  docker: { closed: FolderDocker, opened: FolderDocker },
  docs: { closed: FolderDocuments, opened: FolderDocuments },
  documentation: { closed: FolderDocuments, opened: FolderDocuments },
  helpers: { closed: FolderHelpers, opened: FolderHelpers },
  hooks: { closed: FolderHooks, opened: FolderHooks },
  images: { closed: FolderImages, opened: FolderImages },
  img: { closed: FolderImages, opened: FolderImages },
  assets: { closed: FolderAssets, opened: FolderAssets },
  interfaces: { closed: FolderInterfaces, opened: FolderInterfaces },
  types: { closed: FolderInterfaces, opened: FolderInterfaces },
  layout: { closed: FolderLayout, opened: FolderLayout },
  layouts: { closed: FolderLayout, opened: FolderLayout },
  models: { closed: FolderModels, opened: FolderModels },
  modules: { closed: FolderModules, opened: FolderModules },
  node_modules: { closed: FolderNodeModules, opened: FolderNodeModules },
  prisma: { closed: FolderPrisma, opened: FolderPrisma },
  providers: { closed: FolderProviders, opened: FolderProviders },
  components: { closed: FolderReact, opened: FolderReact },
  routes: { closed: FolderRouter, opened: FolderRouter },
  router: { closed: FolderRouter, opened: FolderRouter },
  services: { closed: FolderServices, opened: FolderServices },
  shared: { closed: FolderShared, opened: FolderShared },
  supabase: { closed: FolderSupabase, opened: FolderSupabase },
  utils: { closed: FolderUtils, opened: FolderUtils },
  util: { closed: FolderUtils, opened: FolderUtils },
  ".husky": { closed: FolderLock, opened: FolderLock },
  scripts: { closed: FolderJs, opened: FolderJs },
};

const SPECIAL_FILE_FOLDER_ICONS: Record<string, IconComponent> = {
  // Files like `.git/` would be folders, but in the registry above we treat
  // them as both: NAMED_FOLDER_ICONS handles the closed/opened pair.
};
void SPECIAL_FILE_FOLDER_ICONS;

export function getFileIconComponent(filename: string): IconComponent {
  const lower = filename.toLowerCase();
  const named = NAMED_FILE_ICONS[lower];
  if (named) return named;
  const dot = lower.lastIndexOf(".");
  if (dot < 0) return Document;
  const ext = lower.slice(dot + 1);
  return EXTENSION_ICONS[ext] ?? Document;
}

export function getFolderIconComponent(
  folderName: string,
  expanded: boolean,
): IconComponent {
  const named = NAMED_FOLDER_ICONS[folderName.toLowerCase()];
  if (named) return expanded ? named.opened : named.closed;
  return expanded ? FolderOpen : Folder;
}
