import type { AgentIntegrationManifest } from "../agent-integrations.js";

export const OPENCODE_AGENT_INTEGRATION = {
  runtimeId: "opencode",
  hookAgent: "opencode",
  label: "OpenCode",
  iconKey: "agent",
  commandLine: "opencode",
  appendEnter: true,
  tier: "native-managed",
  expectedProcesses: ["opencode"],
  detectCommands: ["opencode"],
  installStrategies: [
    {
      kind: "shim-wrapper",
      activation: "preset-launch",
      writesUserConfig: false,
      reversible: true,
    },
    {
      kind: "plugin-overlay",
      activation: "preset-launch",
      writesUserConfig: false,
      reversible: true,
    },
  ],
  events: {
    "session.created": "noop",
    "session.updated": "noop",
    "session.diff": "noop",
    "session.status:active": { lifecycle: "running" },
    "session.status:busy": { lifecycle: "running" },
    "session.status:idle": { lifecycle: "completed" },
    "session.status:error": { lifecycle: "completed" },
    "session.status:retry": { lifecycle: "running" },
    "session.idle": { lifecycle: "completed" },
    "session.error": { lifecycle: "completed" },
    "permission.asked": { lifecycle: "waiting" },
    "permission.replied": { lifecycle: "running" },
    "question.asked": { lifecycle: "waiting" },
    "question.replied": { lifecycle: "running" },
    "question.rejected": { lifecycle: "running" },
    "tool.execute.before": { lifecycle: "running" },
    "tool.execute.after": { lifecycle: "running" },
    "message.updated": "noop",
    "message.part.updated": "noop",
    "message.part.delta": "noop",
  },
} as const satisfies AgentIntegrationManifest;
