import { PaGlyph as corePaGlyph } from "./PaGlyph.js";
import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CameraIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleOffIcon,
  CirclePlusIcon,
  CornerDownLeftIcon,
  HistoryLoadingIcon,
  ImageLibraryIcon,
  KeyboardIcon,
  KeyCtrlIcon,
  KeyEscIcon,
  KeyTabIcon,
  LinkIcon,
  RedoIcon,
  SpinnerIcon,
  UndoIcon,
} from "./SupplementalGlyphs.js";

export {
  FillIcon,
  ICON_BASE_CLASS,
  ICON_SIZE,
  ICON_STROKE_WIDTH,
  StrokeIcon,
} from "./IconBase.js";
export {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CameraIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleOffIcon,
  CirclePlusIcon,
  CornerDownLeftIcon,
  HistoryLoadingIcon,
  ImageLibraryIcon,
  KeyboardIcon,
  KeyCtrlIcon,
  KeyEscIcon,
  KeyTabIcon,
  LinkIcon,
  RedoIcon,
  SpinnerIcon,
  UndoIcon,
};

export const PaGlyph = {
  ...corePaGlyph,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowUp: ArrowUpIcon,
  camera: CameraIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  circleOff: CircleOffIcon,
  circlePlus: CirclePlusIcon,
  cornerDownLeft: CornerDownLeftIcon,
  historyLoading: HistoryLoadingIcon,
  imageLibrary: ImageLibraryIcon,
  keyboard: KeyboardIcon,
  keyCtrl: KeyCtrlIcon,
  keyEsc: KeyEscIcon,
  keyTab: KeyTabIcon,
  link: LinkIcon,
  redo: RedoIcon,
  spinner: SpinnerIcon,
  undo: UndoIcon,
} as const;

export type PaGlyphName = keyof typeof PaGlyph;
